### ISSUE TITLE
jquery not loading if I use DataTable.use(DataTablesLib)

### ISSUE THREAD

**Issue by PeterPilley** [DataTables/Vue#10]
Hi Thanks heaps for doing this component.

If I follow the blog post for using datatables in vue3 I am getting a blank screen and an error 

Uncaught TypeError: Cannot set properties of undefined (setting '$')
    at DataTable (jquery.dataTables.mjs:61:9)
    at Comp.use (datatables.net-vue.esm.js:26527:3)
    at eval (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-cli-plugin-quasar/lib/loader.js.transform-quasar-imports.js!./node_modules/vue-cli-plugin-quasar/lib/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/components/logging.vue?vue&type=script&lang=js:14:61)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-cli-plugin-quasar/lib/loader.js.transform-quasar-imports.js!./node_modules/vue-cli-plugin-quasar/lib/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/components/logging.vue?vue&type=script&lang=js (app.js:63:1)
    at __webpack_require__ (app.js:1344:33)
    at fn (app.js:1635:21)

If I remove DataTable.use the tables load fine but I cannot use any plugins.

I have gone through the messageboard do I need to refer to $ directly in the jquery library as I thought the component included jquery.

Library
    "datatables.net": "^1.13.1",
    "datatables.net-buttons": "^2.3.3",
    "datatables.net-dt": "^1.13.1",
    "datatables.net-select": "^1.5.0",
    "datatables.net-vue3": "^1.0.0",
    "vue": "^3.2.44",

**Comment by PeterPilley** [comment]
Re-read the article and it reports you are using datatables.net-vued ^2.0.0 I have upgraded to that and removed datatables.net and it is now working correctly 

sorry
